# Discover Nightly

name: geos-discover-tier1

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  run-geos-discover-tier1:
    uses: GEOS-ESM/CI-workflows/.github/workflows/geos-discover-tier1.yml@main
