# SWELL Discover HOFX

name: swell-discover-hofx

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  validate-workflow:
  
    runs-on: ubuntu-latest
    steps:
      - name: validate
        uses: GEOS-ESM/CI-workflows/.github/workflows/discover-validate.yml@main
        with:
          accessor: ${{ github.triggering_actor }}
          project: swell
          
      - name: set-env
        run: echo "CI_TEST=yay" >> $GITHUB_ENV
        
  test-environment:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: check-vars
        run: |
          echo ${{ vars.CI_ROOT }}
          echo $CI_TEST
