# SWELL Discover HOFX

name: swell-discover-hofx

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  validate-workflow:
    uses: GEOS-ESM/CI-workflows/.github/workflows/discover-validate.yml@main
    with:
      accessor: ${{ github.triggering_actor }}
      project: swell
