# SWELL Discover Nightly

name: swell-discover-nightly

on:
  workflow_dispatch:
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  swell-discover-nightly:
    uses: GEOS-ESM/CI-workflows/.github/workflows/swell-discover-nightly-test.yml@main
